###############################################################################
# Start of stack config
###############################################################################
# Project Name
name: ${PROJECT_NAME}

networks:
  proxy:
    name: ${PROXY_NETWORK}
    external: true
  frontend:
    name: ${PROJECT_NAME}_frontend
    internal: false
    driver_opts:
      encrypted: "true"
  backend:
    name: ${PROJECT_NAME}_backend
    internal: true
    driver_opts:
      encrypted: "true"
  socket_proxy:
    name: ${PROJECT_NAME}_socket_proxy
    internal: true
    driver_opts:
      encrypted: "true"

services:

  traefik:
    extends:
      file: ../../containers/traefik/compose.yaml
      service: .traefik
    hostname: ${PROJECT_NAME}.${SERVER_NAME}.${SUB_DOMAIN_NAME}${DOMAIN_NAME}  
    container_name: ${PROJECT_NAME}
    depends_on:
      socket-proxy:
        condition: service_healthy
      error-pages:
        condition: service_healthy

  error-pages:
    extends:
      file: ../../containers/error-pages/compose.yaml
      service: .error-pages

  socket-proxy:
    extends:
      file: ../../containers/socket-proxy/compose.yaml
      service: .socket-proxy
    environment:
      CONTAINERS: 1 #optional
      EVENTS: 1 #optional
      INFO: 1 #optional
      LOG_LEVEL: err #optional
      NETWORKS: 1 #optional
      NODES: 1 #optional
      PING: 1 #optional
      SERVICES: 1 #optional
      TASKS: 1 #optional
      VERSION: 1 #optional

  logrotate:
    extends:
      file: ../../containers/logrotate/compose.yaml
      service: .logrotate
    depends_on:
      traefik:
        condition: service_healthy
      socket-proxy-rw:
        condition: service_healthy

  socket-proxy-rw:
    extends:
      file: ../../containers/socket-proxy/compose.yaml
      service: .socket-proxy-rw
    environment:
      CONTAINERS: 1 #optional
      INFO: 1 #optional
      LOG_LEVEL: err #optional
      PING: 1 #optional
      POST: 1 #optional
      VERSION: 1 #optional

  redis:
    extends:
      file: ../../containers/redis/compose.yaml
      service: .redis-public

  traefik-kop:
    extends:
      file: ../../containers/traefik-kop/compose.yaml
      service: .traefik-kop
    depends_on:
      redis:
        condition: service_healthy  

  vmagent:
    extends:
      file: ../../containers/vmagent/compose.yaml
      service: .vmagent-traefik

  vlagent:
    extends:
      file: ../../containers/vlagent/compose.yaml
      service: .vlagent

  vector:
    extends:
      file: ../../containers/vector/compose.yaml
      service: .vector-traefik
