###############################################################################
#region Default configs
###############################################################################

  #####################################
  # Container base defaults
  #####################################
  # Max Usage Limits
x-limits: &limits
  mem_limit: ${MEM_LIMIT:-2G} # Override per container if necessary
  memswap_limit: ${MEM_SWAP_LIMIT:-2.5G}
  mem_reservation: ${MEM_RESERVATION:-64M}
  pids_limit: ${PIDS_LIMIT:-200}
  cpus: ${CPUS_LIMIT:-2} # Set below the total number of cores, for example 3.5 for 4 cores

  # Restart Settings
x-restart: &restart
  stop_grace_period: ${RESTART_GRACE:-1m}
  restart: ${RESTART_MODE:-unless-stopped}

  # Configure security
x-security: &security
  security_opt:
   - no-new-privileges=${NO_NEW_PRIVILEGES:-true}

  # Configure User
x-user: &user
  user: ${PUID:-1000}:${PGID:-1000}

  # Configure Logging
x-logging: &logging
  logging:
    options:
      max-size: ${LOG_MAX_SIZE:-10m}
      max-file: ${LOG_MAX_FILE:-3}

  ## All base defaults in one
x-base: &default-base
  <<: [*limits, *restart, *security, *user, *logging]

  #####################################
  # Container healthcheck defaults
  #####################################
x-healthcheck: &default_healthcheck
  interval: ${HEALTH_INTERVAL:-60s}
  timeout: ${HEALTH_TIMEOUT:-10s}
  retries: ${HEALTH_RETRIES:-5}
  start_period: ${HEALTH_START:-10s}
  
  #####################################
  # Container environment defaults
  #####################################
x-environment-tz: &environment_tz
  TZ: ${TZ:-America/Chicago}

x-environment-user: &environment_user
  PUID: ${PUID:-1000}
  PGID: ${PGID:-1000}

  ## All environment defaults in one
x-environment: &default_environment
  <<: [*environment_tz, *environment_user]
  
#endregion
###############################################################################
#region Stack config
###############################################################################

services:

  .grafana:
    <<: [*limits, *restart, *security, *user, *logging]
    image: ${GRAFANA_IMAGE:-grafana/grafana}:${GRAFANA_VERSION:-latest}
    hostname: ${PROJECT_NAME}-${GRAFANA_HOSTNAME}.${SERVER_NAME}.${SUB_DOMAIN_NAME}${DOMAIN_NAME}
    container_name: "${PROJECT_NAME}-${GRAFANA_HOSTNAME}"
    #ports:
    #  - 3000:3000
    environment:
      <<: [*environment_tz, *environment_user]
      VMAUTH_USER: ${VMAUTH_USER}
      VMAUTH_PASS: ${VMAUTH_PASS}
      GF_PLUGINS_PREINSTALL: victoriametrics-logs-datasource, victoriametrics-metrics-datasource
      GF_INSTALL_PLUGINS: victoriametrics-logs-datasource, victoriametrics-metrics-datasource
      GF_LOG_FORMAT: json
    volumes:
      - ${DOCKER_VOLUMES}/${PROJECT_NAME}/grafana-data:/var/lib/grafana
      - ./config/datasources/victoriametrics.yml:/etc/grafana/provisioning/datasources/victoriametrics.yml
      - ./config/provisioning:/etc/grafana/provisioning/dashboards
      - ./config/dashboards:/var/lib/grafana/dashboards
      #- ./grafana-config/dashboards/victorialogs.json:/var/lib/grafana/dashboards/vl.json
    labels: ## Traefik Labels
      - "traefik.enable=true"
      - "traefik.docker.network=${PROXY_NETWORK}"
        ## HTTP Routers
      - "traefik.http.routers.$PROJECT_NAME-grafana-rtr.rule=
        Host(`${GRAFANA_HOSTNAME}.${DOMAIN_NAME}`) ||
        Host(`${GRAFANA_HOSTNAME}.${SUB_DOMAIN_NAME}${DOMAIN_NAME}`) ||
        Host(`${GRAFANA_HOSTNAME}.${SERVER_NAME}.${SUB_DOMAIN_NAME}${DOMAIN_NAME}`) ||
        Host(`${PROJECT_NAME}-${GRAFANA_HOSTNAME}.${SERVER_NAME}.${SUB_DOMAIN_NAME}${DOMAIN_NAME}`)"
        ## Middlewares
      - "traefik.http.routers.$PROJECT_NAME-grafana-rtr.middlewares=chain-no-auth@file"
        ## HTTP Services
      - "traefik.http.services.$PROJECT_NAME-grafana-svc.loadbalancer.server.port=3000"
      ## Komodo Labels
      - "komodo.skip" # Prevent Komodo from stopping with StopAllContainers
    networks:
      - proxy
      - frontend # For internet access for dashboard and plugin downlaods, and for external datasources.
      - backend
    depends_on:
      victorialogs:
        condition: service_healthy
      victoriametrics:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000/api/health"]
      <<: *default_healthcheck