###############################################################################
# Start of stack config
###############################################################################
# Project Name
name: ${PROJECT_NAME}

networks:
#  proxy:
#    name: ${PROXY_NETWORK}
#    external: true
  frontend:
    name: ${PROJECT_NAME}_frontend
    internal: false
  backend:
    name: ${PROJECT_NAME}_backend
    internal: true
  socket_proxy:
    name: ${PROJECT_NAME}_socket_proxy
    internal: true

services:

  crowdsec-server:
    extends:
      file: ../../containers/crowdsec/compose.yaml
      service: .crowdsec-server

  postgres:
    extends:
      file: ../../containers/postgres/compose.yaml
      service: .postgres

  socket-proxy:
    extends:
      file: ../../containers/socket-proxy/compose.yaml
      service: .socket-proxy
    environment:
      CONTAINERS: 1 #optional
      EVENTS: 1 #optional
      INFO: 1 #optional
      PING: 1 #optional
      VERSION: 1 #optional