###############################################################################
# Start of stack config
###############################################################################
# Project Name: "system"
name: ${PROJECT_NAME}

networks:
  frontend:
    name: ${PROJECT_NAME}_frontend
    internal: false
  backend:
    name: ${PROJECT_NAME}_backend
    internal: true
  socket_proxy:
    name: ${PROJECT_NAME}_socket_proxy
    internal: true

services:

## VictoriaMetrics Related Services
  vmagent:
    extends:
      file: ../../containers/vmagent/compose.yaml
      service: .vmagent-system

  vlagent:
    extends:
      file: ../../containers/vlagent/compose.yaml
      service: .vlagent

  vector:
    extends:
      file: ../../containers/vector/compose.yaml
      service: .vector-system
    depends_on:
      socket-proxy:
        condition: service_healthy
      vlagent:
        condition: service_healthy
      vmagent:
        condition: service_healthy

  cadvisor:
    extends:
      file: ../../containers/cadvisor/compose.yaml
      service: .cadvisor

## Dozzle Related Services
  dozzle-agent:
    extends:
      file: ../../containers/dozzle/compose.yaml
      service: .dozzle-agent
    depends_on:
      socket-proxy:
        condition: service_healthy

## Dockns Related Services
  dockns:
    extends:
      file: ../../containers/dockns/compose.yaml
      service: .dockns
    depends_on:
      socket-proxy:
        condition: service_healthy

## Support Services
  socket-proxy:
    extends:
      file: ../../containers/socket-proxy/compose.yaml
      service: .socket-proxy
    environment:
      CONTAINERS: 1 #optional
      EVENTS: 1 #optional
      INFO: 1 #optional
      NETWORKS: 1 #optional
      NODES: 1 #optional
      PING: 1 #optional
      SERVICES: 1 #optional
      TASKS: 1 #optional
      VERSION: 1 #optional
