###############################################################################
# Start of stack config
###############################################################################
# Project Name
name: ${PROJECT_NAME}

networks:
#  proxy:
#    name: ${PROXY_NETWORK}
#    external: true
  frontend:
    name: ${PROJECT_NAME}_frontend
    internal: false
  backend:
    name: ${PROJECT_NAME}_backend
    internal: true
  socket_proxy:
    name: ${PROJECT_NAME}_socket_proxy
    internal: true

services:

  vlagent:
    extends:
      file: ../../containers/vlagent/compose.yaml
      service: .vlagent-host

  vmagent:
    extends:
      file: ../../containers/vmagent/compose.yaml
      service: .vmagent-host

  vector:
    extends:
      file: ../../containers/vector/compose.yaml
      service: .vector-host

  cadvisor:
    extends:
      file: ../../containers/cadvisor/compose.yaml
      service: .cadvisor-host

  socket-proxy:
    extends:
      file: ../../containers/socket-proxy/compose.yaml
      service: .socket-proxy
    environment:
      CONTAINERS: 1 #optional
      EVENTS: 1 #optional
      INFO: 1 #optional
      PING: 1 #optional
      POST: 1 #optional
      VERSION: 1 #optional