###############################################################################
#region Default configs
###############################################################################

  #####################################
  # Container base defaults
  #####################################
  # Max Usage Limits
x-limits: &limits
  mem_limit: ${MEM_LIMIT:-2G} # Override per container if necessary
  memswap_limit: ${MEM_SWAP_LIMIT:-2.5G}
  mem_reservation: ${MEM_RESERVATION:-64M}
  pids_limit: ${PIDS_LIMIT:-200}
  cpus: ${CPUS_LIMIT:-2} # Set below the total number of cores, for example 3.5 for 4 cores

  # Restart Settings
x-restart: &restart
  stop_grace_period: ${RESTART_GRACE:-1m}
  restart: ${RESTART_MODE:-unless-stopped}

  # Configure security
x-security: &security
  security_opt:
    - no-new-privileges=${NO_NEW_PRIVILEGES:-true}

  # Configure User
x-user: &user
  user: ${PUID:-1000}:${PGID:-1000}

  # Configure Logging
x-logging: &logging
  logging:
    options:
      max-size: ${LOG_MAX_SIZE:-10m}
      max-file: ${LOG_MAX_FILE:-3}

  ## All base defaults in one
x-base: &default-base
  <<: [*limits, *restart, *security, *user, *logging]

  #####################################
  # Container healthcheck defaults
  #####################################
x-healthcheck: &default_healthcheck
  interval: ${HEALTH_INTERVAL:-60s}
  timeout: ${HEALTH_TIMEOUT:-10s}
  retries: ${HEALTH_RETRIES:-5}
  start_period: ${HEALTH_START:-10s}

  #####################################
  # Container environment defaults
  #####################################
x-environment-tz: &environment_tz
  TZ: ${TZ:-America/Chicago}

x-environment-user: &environment_user
  PUID: ${PUID:-1000}
  PGID: ${PGID:-1000}

  ## All environment defaults in one
x-environment: &default_environment
  <<: [*environment_tz, *environment_user]

#endregion
###############################################################################
#region Stack config
###############################################################################

services:

  .imageName:
    <<: [*limits, *restart, *security, *user, *logging]
    image: imageName:latest
    hostname: ${PROJECT_NAME}-${IMAGENAME_HOSTNAME}.${SERVER_NAME}.${SUB_DOMAIN_NAME}${DOMAIN_NAME}
    container_name: "${PROJECT_NAME}-${IMAGENAME_HOSTNAME}"
    command:
      - "COMMAND"
    ports:
      - "PORT:PORT"
    environment:
      <<: [*environment_tz, *environment_user]
    volumes:
      - "./config:/config"
      - ${DOCKER_LOGS}/${PROJECT_NAME}/imageName:/logs"
      - ${DOCKER_VOLUMES}/${PROJECT_NAME}/imageName-data:/data"
    labels: ## Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=${PROXY_NETWORK}"
        ## HTTP Routers
      - "traefik.http.routers.$PROJECT_NAME-rtr.rule=
        Host(`${IMAGENAME_SERVICE_NAME}.${DOMAIN_NAME}`) ||
        Host(`${IMAGENAME_SERVICE_NAME}.${SUB_DOMAIN_NAME}${DOMAIN_NAME}`) ||
        Host(`${IMAGENAME_SERVICE_NAME}.${SERVER_NAME}.${SUB_DOMAIN_NAME}${DOMAIN_NAME}`) ||
        Host(`${IMAGENAME_HOSTNAME}.${SERVER_NAME}.${SUB_DOMAIN_NAME}${DOMAIN_NAME}`) ||
        Host(`${PROJECT_NAME}.${SERVER_NAME}.${SUB_DOMAIN_NAME}${DOMAIN_NAME}`)"
        ## Middlewares
      - "traefik.http.routers.$PROJECT_NAME-rtr.middlewares=chain-no-auth@file"
        ## HTTP Services
      - "traefik.http.services.$PROJECT_NAME-svc.loadbalancer.server.port=9120"

      ## Traefik-KOP Labels
      - "kop-public.traefik.enable=true"
       ## HTTP Routers
      - "kop-public.traefik.http.routers.$PROJECT_NAME-kop-rtr.rule=
        Host(`${IMAGENAME_SERVICE_NAME}.${DOMAIN_NAME}`) ||
        Host(`${IMAGENAME_SERVICE_NAME}.${SUB_DOMAIN_NAME}${DOMAIN_NAME}`) ||
        Host(`${IMAGENAME_SERVICE_NAME}.${SERVER_NAME}.${SUB_DOMAIN_NAME}${DOMAIN_NAME}`) ||
        Host(`${IMAGENAME_HOSTNAME}.${SERVER_NAME}.${SUB_DOMAIN_NAME}${DOMAIN_NAME}`) ||
        Host(`${PROJECT_NAME}.${SERVER_NAME}.${SUB_DOMAIN_NAME}${DOMAIN_NAME}`)"
      ## Middlewares
      - "kop-public.traefik.http.routers.$PROJECT_NAME-kop-rtr.middlewares=chain-no-auth@file"
       ## HTTP Services
        # This is needed to force https:// instead of http://<URL>:80
      - "kop-public.traefik.http.services.$PROJECT_NAME-kop-svc.loadbalancer.server.url=https://${IMAGENAME_SERVICE_NAME}"
        # This is needed otherwise loadbalancer.server.url is https://<IP>
      - "kop.bind.ip=${IMAGENAME_SERVICE_NAME}.${SERVER_NAME}.${SUB_DOMAIN_NAME}${DOMAIN_NAME}"

      ## DockNS Labels
      ### Cloudflare Records
      - "dockns.cloudflare.record=A"
      - "dockns.cloudflare.name=${IMAGENAME_SERVICE_NAME}.${DOMAIN_NAME}"

      ### Technitium Records
      - "dockns.technitium.0.record=CNAME"
      - "dockns.technitium.0.name=${IMAGENAME_SERVICE_NAME}.${SUB_DOMAIN_NAME}${DOMAIN_NAME}"
      - "dockns.technitium.1.record=CNAME"
      - "dockns.technitium.1.name=${IMAGENAME_HOSTNAME}.${SUB_DOMAIN_NAME}${DOMAIN_NAME}"

    networks:
      - proxy
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "", ""]
      <<: *default_healthcheck