###############################################################################
#region Default configs
###############################################################################

  #####################################
  # Container base defaults
  #####################################
  # Max Usage Limits
x-limits: &limits
  mem_limit: ${MEM_LIMIT:-2G} # Override per container if necessary
  memswap_limit: ${MEM_SWAP_LIMIT:-2.5G}
  mem_reservation: ${MEM_RESERVATION:-64M}
  pids_limit: ${PIDS_LIMIT:-200}
  cpus: ${CPUS_LIMIT:-2} # Set below the total number of cores, for example 3.5 for 4 cores

  # Restart Settings
x-restart: &restart
  stop_grace_period: ${RESTART_GRACE:-1m}
  restart: ${RESTART_MODE:-unless-stopped}

  # Configure security
x-security: &security
  security_opt:
    - no-new-privileges=${NO_NEW_PRIVILEGES:-true}

  # Configure User
x-user: &user
  user: ${PUID:-1000}:${PGID:-1000}

  # Configure Logging
x-logging: &logging
  logging:
    options:
      max-size: ${LOG_MAX_SIZE:-10m}
      max-file: ${LOG_MAX_FILE:-3}

  ## All base defaults in one
x-base: &default-base
  <<: [*limits, *restart, *security, *user, *logging]

  #####################################
  # Container healthcheck defaults
  #####################################
x-healthcheck: &default_healthcheck
  interval: ${HEALTH_INTERVAL:-60s}
  timeout: ${HEALTH_TIMEOUT:-10s}
  retries: ${HEALTH_RETRIES:-5}
  start_period: ${HEALTH_START:-10s}

  #####################################
  # Container environment defaults
  #####################################
x-environment-tz: &environment_tz
  TZ: ${TZ:-America/Chicago}

x-environment-user: &environment_user
  PUID: ${PUID:-1000}
  PGID: ${PGID:-1000}

  ## All environment defaults in one
x-environment: &default_environment
  <<: [*environment_tz, *environment_user]

#endregion
###############################################################################
#region Stack config
###############################################################################

services:
  .error-pages:
    <<: [*limits, *restart, *security, *user, *logging]
    image: tarampampam/error-pages:latest
    hostname: ${PROJECT_NAME}-${ERROR_PAGES_HOSTNAME}.${SERVER_NAME}.${SUB_DOMAIN_NAME}${DOMAIN_NAME}
    container_name: ${PROJECT_NAME}-${ERROR_PAGES_HOSTNAME}
    environment:
      <<: [*environment_tz, *environment_user]
      TEMPLATE_NAME: lost-in-space
    labels:
      - traefik.enable=true
      - traefik.docker.network=${PROJECT_NAME}_backend

      # use as default "fallback" for any non-registered services (with priority below normal)
      - traefik.http.routers.error-pages-rtr.rule=HostRegexp(`.+`)
      - traefik.http.routers.error-pages-rtr.priority=10
      - traefik.http.routers.error-pages-rtr.middlewares=middlewares-error-pages

      # "errors" middleware settings
      - traefik.http.middlewares.middlewares-error-pages.errors.status=400-599
      - traefik.http.middlewares.middlewares-error-pages.errors.service=error-pages-svc
      - traefik.http.middlewares.middlewares-error-pages.errors.query=/{status}.html

      # define service properties
      - traefik.http.services.error-pages-svc.loadbalancer.server.port=8080
    networks:
      - backend
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:8080/"]
      <<: *default_healthcheck