###############################################################################
#region Default configs
###############################################################################

  #####################################
  # Container base defaults
  #####################################
  # Max Usage Limits
x-limits: &limits
  mem_limit: ${MEM_LIMIT:-2G} # Override per container if necessary
  memswap_limit: ${MEM_SWAP_LIMIT:-2.5G}
  mem_reservation: ${MEM_RESERVATION:-64M}
  pids_limit: ${PIDS_LIMIT:-200}
  cpus: ${CPUS_LIMIT:-2} # Set below the total number of cores, for example 3.5 for 4 cores

  # Restart Settings
x-restart: &restart
  stop_grace_period: ${RESTART_GRACE:-1m}
  restart: ${RESTART_MODE:-unless-stopped}

  # Configure security
x-security: &security
  security_opt:
   - no-new-privileges=${NO_NEW_PRIVILEGES:-true}

  # Configure User
x-user: &user
  user: ${PUID:-1000}:${PGID:-1000}

  # Configure Logging
x-logging: &logging
  logging:
    options:
      max-size: ${LOG_MAX_SIZE:-10m}
      max-file: ${LOG_MAX_FILE:-3}

  ## All base defaults in one
x-base: &default-base
  <<: [*limits, *restart, *security, *user, *logging]

  #####################################
  # Container healthcheck defaults
  #####################################
x-healthcheck: &default_healthcheck
  interval: ${HEALTH_INTERVAL:-60s}
  timeout: ${HEALTH_TIMEOUT:-10s}
  retries: ${HEALTH_RETRIES:-5}
  start_period: ${HEALTH_START:-10s}
  
  #####################################
  # Container environment defaults
  #####################################
x-environment-tz: &environment_tz
  TZ: ${TZ:-America/Chicago}

x-environment-user: &environment_user
  PUID: ${PUID:-1000}
  PGID: ${PGID:-1000}

  ## All environment defaults in one
x-environment: &default_environment
  <<: [*environment_tz, *environment_user]
  
#endregion
###############################################################################
#region Stack config
###############################################################################

services:

  .vector:
    <<: [*limits, *restart, *security, *logging]
    image: docker.io/timberio/vector:0.52.X-debian
    hostname: ${PROJECT_NAME}-${VECTOR_HOSTNAME}.${SERVER_NAME}.${SUB_DOMAIN_NAME}${DOMAIN_NAME}
    container_name: "${PROJECT_NAME}-${VECTOR_HOSTNAME}"
    #ports:
    #  - "8686:8686"
    environment:
      <<: [*environment_tz, *environment_user]
      VECTOR_LOG_FORMAT: json
      VECTOR_LOG: info
    volumes:
      - ${DOCKER_VOLUMES}/${PROJECT_NAME}/vector-data:/var/lib/vector
    labels: ## Komodo Labels
      - "komodo.skip" # Prevent Komodo from stopping with StopAllContainers
    networks:
      - backend
    depends_on:
      vlagent:
        condition: service_healthy
      vmagent:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/usr/bin/vector", "validate", "--skip-healthchecks"]
      <<: *default_healthcheck

  .vector-traefik:
    extends: .vector
    <<: [*user]
    environment:
    volumes:
      - ./config/vector-traefik.yml:/etc/vector/vector.yaml:ro
      - ${DOCKER_LOGS}/${PROJECT_NAME}/traefik:/var/log/traefik/:ro
    depends_on:
      traefik:
        condition: service_healthy

  .vector-host:
    extends: .vector
    ports:
      - "5140:5140/udp"
      - "5140:5140/tcp"
    environment:
      DOCKER_HOST: tcp://${PROJECT_NAME}-${SOCKET_PROXY_HOSTNAME}:2375
    volumes:
      - ./config/vector-host.yml:/etc/vector/vector.yaml:ro
      # Volumes for host log collection
      - /etc/machine-id:/etc/machine-id:ro
      - /var/log:/var/log:ro
      - /run/log/journal:/run/log/journal:ro
    networks:
      - frontend
      - socket_proxy
    userns_mode: "host"
